# Generated by Django 6.0 on 2026-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
